### ISSUE TITLE
ORMLITE CONFLICT

### ISSUE THREAD

**Issue by fedesobral** [SnowdreamFramework/android-autoupdater#9]
Hi,

I am using ormlite on my project and i'm having some trouble using your project.
Everything seems fine until i click to update the apk, there the app crashes with this error:

    04-14 17:25:43.199  27004-27004/com.myproject E/AndroidRuntime﹕ FATAL EXCEPTION: main
        Process: com.myproject, PID: 27004
        java.lang.IllegalStateException: Helper class was class com.myproject.storage.DBHelper but is trying to be reset to class com.github.snowdream.android.app.dao.DatabaseHelper
                at com.j256.ormlite.android.apptools.OpenHelperManager.innerSetHelperClass(OpenHelperManager.java:155)
                at com.j256.ormlite.android.apptools.OpenHelperManager.getHelper(OpenHelperManager.java:77)
                at com.github.snowdream.android.app.dao.ISqlImpl.getHelper(ISqlImpl.java:58)
                at com.github.snowdream.android.app.dao.ISqlImpl.queryDownloadTask(ISqlImpl.java:92)
                at com.github.snowdream.android.app.DownloadManager.start(DownloadManager.java:221)
                at com.autoupdater.UpdateManager.informUpdate(UpdateManager.java:272)
                at com.autoupdater.UpdateManager.access$400(UpdateManager.java:26)
                at com.autoupdater.UpdateManager$UIHandler.handleMessage(UpdateManager.java:361)
                at android.os.Handler.dispatchMessage(Handler.java:102)
                at android.os.Looper.loop(Looper.java:135)
                at android.app.ActivityThread.main(ActivityThread.java:5312)
                at java.lang.reflect.Method.invoke(Native Method)
                at java.lang.reflect.Method.invoke(Method.java:372)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

It seems that my DBHelper class is conflicting with yours. How can i fix this?
Thank you

**Comment by snowdream** [comment]
@fedesobral 

1. http://stackoverflow.com/questions/17300571/using-multiple-database-helpers-in-android-ormlite
2. https://github.com/j256/ormlite-examples/tree/master/android/HelloAndroidTwoDbs

**Comment by fedesobral** [comment]
Hi @snowdream,

Thank you for your quick reply, however this is not a possible solution as i do not have access to the project where you use ormlite so i cannot modify your helper, it is a .jar, plus i do not feel confident modifying your project

**Comment by snowdream** [comment]
@fedesobral I will check it later.

**Comment by klifa90** [comment]
I am having the exact same problem!

Thank you @snowdream
